version: "3"
services:

  nodejs:
    build: ./nodejs
    container_name: docker-nodejs
    depends_on: 
    - mariadb
    environment:
      - MYSQL_HOST_IP= mariadb
    ports:
      - 8000:8000
    volumes:
      - ./nodejs:/app
    links: 
     - mariadb
    command: npm start
  
  react-front:
    build: ./react-front
    container_name: docker-react-front
    environment: 
      <<: *common-variables
      NODE_PATH: src
    ports: 
    - 3000:3000
    volumes: 
    - /.react-front/src:/app/src
    links: 
    - docker-nodejs
    command: npm start



