version: "3"
services:

  nodejs:
    build: ./nodejs
    container_name: docker-nodejs
    ports:
      - 3001:3001
    volumes:
      - ./nodejs:/app
    command: npm start
  
  react-front:
    build: ./react-front
    container_name: docker-react-front
    ports: 
    - 3000:3000
    volumes: 
    - ./react-front/src:/app/src
    links: 
    - docker-nodejs
    command: npm start
    



